name: TSB
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1t=h7f8727e_0
  - pip=22.3.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py38h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
      - absl-py==1.4.0
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - astunparse==1.6.3
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - cachetools==5.3.0
      - cffi==1.15.1
      - charset-normalizer==3.0.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - dask==2023.2.1
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.13
      - distributed==2023.2.1
      - docopt==0.6.2
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - flatbuffers==23.1.21
      - fonttools==4.38.0
      - fqdn==1.5.1
      - fsspec==2023.1.0
      - gast==0.4.0
      - google-auth==2.16.2
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.3
      - h5py==3.8.0
      - heapdict==1.0.1
      - idna==3.4
      - importlib-metadata==6.0.0
      - importlib-resources==5.12.0
      - ipykernel==6.22.0
      - ipython==8.11.0
      - ipython-genutils==0.2.0
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - joypy==0.2.6
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - keras==2.11.0
      - keras-tuner==1.3.0
      - kerastuner-tensorboard-logger==0.2.3
      - kiwisolver==1.4.4
      - kt-legacy==1.0.4
      - libclang==15.0.6.1
      - llvmlite==0.38.1
      - locket==1.0.0
      - markdown==3.4.1
      - markupsafe==2.1.2
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.6
      - matrixprofile==1.1.10
      - mistune==2.0.5
      - msgpack==1.0.4
      - natsort==8.2.0
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.3.1
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numba==0.55.2
      - numpy==1.22.4
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.0
      - pandas==1.5.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - partd==1.3.0
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - pipreqs==0.4.11
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.5.0
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - protobuf==3.11.2
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
      - pygments==2.14.0
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2022.7.1
      - pyyaml==6.0
      - pyzmq==25.0.2
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rsa==4.9
      - scikit-learn==1.2.0
      - scipy==1.10.1
      - seaborn==0.12.2
      - send2trash==1.8.2
      - silence-tensorflow==1.2.1
      - six==1.16.0
      - sktime==0.15.1
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - statsmodels==0.13.5
      - stumpy==1.11.1
      - support-developer==1.0.5
      - tblib==1.7.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.2.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - toolz==0.12.0
      - torch==1.13.1+cu116
      - torchaudio==0.13.1+cu116
      - torchvision==0.14.1+cu116
      - tornado==6.2
      - tqdm==4.64.1
      - traitlets==5.9.0
      - tsfresh==0.18.0
      - typing-extensions==4.5.0
      - uri-template==1.2.0
      - urllib3==1.26.14
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - werkzeug==2.2.3
      - wrapt==1.15.0
      - yarg==0.1.9
      - zict==2.2.0
      - zipp==3.15.0
prefix: /home/sylli/anaconda3/envs/TSB
